In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!pip install tsfresh

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 KB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.2/136.2 KB 6.7 MB/s eta 0:00:00


In [ ]:
!pip install prophet

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install xgboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install  greykite

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 58.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 85.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.4/102.4 KB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.2/317.2 KB 29.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 KB 23.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 77.0 MB/s eta 0:00:00
  Created wheel for osqp: filename=osqp-0.6.1-cp39-cp39-linux_x86_64.whl size=209941 sha256=fd741be18d1debfe103e8db5e2c1c1b5f8686b5240bc8adaffa13179694d75da
  Stored in directory: /root/.cache/pip/wheels/3d/34/b7/b8b2af435e6e6d4ce9c92611064e6c8589579bbf4148ea4d50
Successfully built osqp
  Attempt

In [21]:
!pip install neuralprophet

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.0/146.0 KB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 19.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 KB 3.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 60.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.2/519.2 KB 47.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.8/827.8 KB 45.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 57.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 KB 631.4 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.1/185.1 KB 20.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
!pip install scalecast

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.3/755.3 KB 12.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.2/216.2 KB 18.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.6/76.6 MB 12.5 MB/s eta 0:00:00
  Created wheel for scalecast: filename=SCALECAST-0.17.12-py3-none-any.whl size=116976 sha256=e4ef2338ebfc51e85390641cdf7017cc95e2260f061fb9dd3850b822ea6d9a3c
  Stored in directory: /root/.cache/pip/wheels/d1/8a/df/e3ff966e425a947721315ccc347c10974249d46c28c3aad465
  Created wheel for eli5: filename=eli5-0.13.0-py2.py3-none-any.whl size=107748 sha256=c7a19d70ecb4f8bf71b27b82cebf11b96df6b72c8af3f06c05f9335f771de2db
  Stored in directory: /root/.cache/pip/wheels/7b/26/a5/8460416695a992a2966b41caa5338e5e7fcea98c9d032d055c
Successfully built scalecast eli5


In [3]:
import pandas as pd
import tsfresh as ts
import numpy as np
from sklearn.model_selection import train_test_split
import os
import glob

ERROR:numba.cuda.cudadrv.driver:Call to cuInit results in CUDA_ERROR_NO_DEVICE


In [4]:
path = os.getcwd()
csv_files = glob.glob(os.path.join('/content/drive/MyDrive/College/Data/Sample Time Series/All', "*.csv"))

In [5]:
csv_files = csv_files[::-1]

In [6]:
df = pd.DataFrame()
count =1
for i in csv_files:
  temp = pd.read_csv(i)
  temp['id'] = count
  df = pd.concat([df,temp])
  count+=1

In [ ]:
df

Unnamed: 0 point_timestamp  point_value  id
0             0      2021-01-11    7312504.0   1
1             1      2021-01-18    7903107.0   1
2             2      2021-01-25    8376171.0   1
3             3      2021-02-01    6440786.0   1
4             4      2021-02-08    7267653.0   1
..          ...             ...          ...  ..
470         470      2023-01-28         27.0  16
471         471      2023-01-29     153181.0  16
472         472      2023-01-30     541232.0  16
473         473      2023-01-31     712411.0  16
474         474      2023-02-01          1.0  16

[5423 rows x 4 columns]

In [ ]:
df.shape

(13100, 4)

In [7]:
df.fillna(method = 'ffill',inplace = True)

In [8]:
df.isna().sum()

Unnamed: 0         0
point_timestamp    0
point_value        0
id                 0
dtype: int64

In [9]:
df = df.iloc[: , 1:]

In [10]:

df_rolled = ts.utilities.dataframe_functions.roll_time_series(df,column_id='id',
                                                                column_sort='point_timestamp',
                                                                  min_timeshift=24,
                                                                  max_timeshift=24)

Rolling: 100%|██████████| 1512/1512 [00:22<00:00, 67.54it/s]


In [ ]:
df_rolled.head()

point_timestamp  point_value               id
0      2020-12-01          2.0  (1, 2020-12-25)
1      2020-12-02          3.0  (1, 2020-12-25)
2      2020-12-03          2.0  (1, 2020-12-25)
3      2020-12-04          3.0  (1, 2020-12-25)
4      2020-12-05          3.0  (1, 2020-12-25)

In [ ]:
df_rolled.isna().sum()

point_timestamp    0
point_value        0
id                 0
dtype: int64

In [ ]:
df_rolled.shape

(306550, 3)

In [ ]:

df_features = ts.extract_features(df_rolled, column_id='id', column_sort='point_timestamp')
df_features.columns


In [11]:

df_features = ts.extract_features(df_rolled, column_id='id', column_sort='point_timestamp', 
                                       default_fc_parameters=ts.feature_extraction.MinimalFCParameters())
df_features.columns


Feature Extraction: 100%|██████████| 5045/5045 [00:06<00:00, 742.91it/s]


Index(['point_value__sum_values', 'point_value__median', 'point_value__mean',
       'point_value__length', 'point_value__standard_deviation',
       'point_value__variance', 'point_value__root_mean_square',
       'point_value__maximum', 'point_value__absolute_maximum',
       'point_value__minimum'],
      dtype='object')

In [ ]:
df_features

point_value__sum_values  point_value__median  \
1  2021-06-28              195613940.0            7907051.0   
   2021-07-05              195763680.0            7907051.0   
   2021-07-12              195853716.0            7993143.0   
   2021-07-19              195982304.0            7993143.0   
   2021-07-26              198440522.0            8036098.0   
...                                ...                  ...   
16 2023-01-28               12845048.0             597146.0   
   2023-01-29               12300852.0             592973.0   
   2023-01-30               12006703.0             562655.0   
   2023-01-31               12096657.0             562655.0   
   2023-02-01               11825929.0             562655.0   

               point_value__mean  point_value__length  \
1  2021-06-28         7824557.60                 25.0   
   2021-07-05         7830547.20                 25.0   
   2021-07-12         7834148.64                 25.0   
   2021-07-19         7839292.16                 25.0   
   2021-07-26         7937620.88                 25.0   
...                          ...                  ...   
16 2023-01-28          513801.92                 25.0   
   2023-01-29          492034.08                 25.0   
   2023-01-30          480268.12                 25.0   
   2023-01-31          483866.28                 25.0   
   2023-02-01          473037.16                 25.0   

               point_value__standard_deviation  point_value__variance  \
1  2021-06-28                    684243.738882           4.681895e+11   
   2021-07-05                    680379.680112           4.629165e+11   
   2021-07-12                    680992.244834           4.637504e+11   
   2021-07-19                    685537.148792           4.699612e+11   
   2021-07-26                    653436.633016           4.269794e+11   
...                                        ...                    ...   
16 2023-01-28                    228490.343282           5.220784e+10   
   2023-01-29                    235770.871044           5.558790e+10   
   2023-01-30                    225456.867122           5.083080e+10   
   2023-01-31                    228396.054569           5.216476e+10   
   2023-02-01                    244121.716087           5.959541e+10   

               point_value__root_mean_square  point_value__maximum  \
1  2021-06-28                   7.854419e+06             8786461.0   
   2021-07-05                   7.860050e+06             8786461.0   
   2021-07-12                   7.863691e+06             8786461.0   
   2021-07-19                   7.869210e+06             8786461.0   
   2021-07-26                   7.964471e+06             8899004.0   
...                                      ...                   ...   
16 2023-01-28                   5.623169e+05              835381.0   
   2023-01-29                   5.456056e+05              835381.0   
   2023-01-30                   5.305547e+05              780589.0   
   2023-01-31                   5.350620e+05              780589.0   
   2023-02-01                   5.323153e+05              780589.0   

               point_value__absolute_maximum  point_value__minimum  
1  2021-06-28                      8786461.0             6271015.0  
   2021-07-05                      8786461.0             6271015.0  
   2021-07-12                      8786461.0             6271015.0  
   2021-07-19                      8786461.0             6271015.0  
   2021-07-26                      8899004.0             6271015.0  
...                                      ...                   ...  
16 2023-01-28                       835381.0                  27.0  
   2023-01-29                       835381.0                  27.0  
   2023-01-30                       780589.0                  27.0  
   2023-01-31                       780589.0                  27.0  
   2023-02-01                       780589.0                   1.0  

[5045 rows x 10 columns]

In [ ]:
df_features.loc[1].shape

(721, 10)

In [ ]:
df_features.shape

(12262, 10)

In [ ]:
df.shape

(13100, 3)

### Models 

## ARIMA

In [ ]:
df.query("id == 1")['point_value']

0      6.0
1      7.0
2      6.0
3      6.0
4      7.0
      ... 
740    7.0
741    7.0
742    7.0
743    8.0
744    7.0
Name: point_value, Length: 745, dtype: float64

In [ ]:
from pylab import rcParams
rcParams['figure.figsize'] = 15, 7
df.query("id == 3").plot()

<AxesSubplot:>

In [12]:
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_predict

In [13]:
from statsmodels.tsa.stattools import adfuller
test_result=adfuller(df.query("id == 5")['point_value'])
test_result[1]

0.12179354387870917

In [14]:
def arima(df_ar):
  test_result=adfuller(df_ar['point_value'])
  train = df_ar['point_value'][:-15]
  test = df_ar['point_value'][-15:]
  model=ARIMA(train,order=(1,0,1))
  model_fit=model.fit()
  #fig, ax = plt.subplots()
  #ax = train.plot(ax=ax)
  #plot_predict(model_fit, ax=ax)
  fc = model_fit.forecast(15, alpha=0.05)  # 95% conf\
  df_test = pd.DataFrame(test)
  test =np.array(df_test.replace(to_replace=0, method='ffill'))
  #print(y_test,preds)
  mape = np.mean(np.abs((np.array(fc) - test)/test))*100
  #plt.show()
  return mape

## Prophet

In [ ]:
from prophet import Prophet

In [ ]:
df

point_timestamp  point_value  id
0        2019-07-14          6.0   1
1        2019-07-15          7.0   1
2        2019-07-16          6.0   1
3        2019-07-17          6.0   1
4        2019-07-18          7.0   1
..              ...          ...  ..
470      2023-01-28         27.0  10
471      2023-01-29     153181.0  10
472      2023-01-30     541232.0  10
473      2023-01-31     712411.0  10
474      2023-02-01          1.0  10

[3345 rows x 3 columns]

In [ ]:
def prophet(df_prp):
  print(df_prp.columns)
  df_prp.rename(columns={'point_timestamp': 'ds', 'point_value': 'y'}, inplace=True)
  train_data = df_prp.sample(frac=0.8, random_state=10)
  validation_data = df_prp.drop(train_data.index)
  train_data = train_data.reset_index()
  validation_data = validation_data.reset_index()
  model = Prophet()
  model.fit(train_data)
  prediction = model.predict(pd.DataFrame({'ds':validation_data['ds']}))
  y_actual = validation_data['y']
  y_predicted = prediction['yhat']
  y_predicted = y_predicted.astype(int)
  df_test = pd.DataFrame(y_actual)
  y_actual =np.array(df_test.replace(to_replace=0, method='ffill'))
  #print(y_test,preds)
  mape = np.mean(np.abs((np.array(y_predicted)- y_actual)/y_actual))*100

  return mape

## XgBoost

In [15]:
import xgboost as xgb

In [16]:
def xgbst(df_xg):
  x = np.array(df_xg.index)
  y = np.array(df_xg['point_value'])
  X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33)
  dtrain_reg = xgb.DMatrix(np.vstack(X_train),np.vstack(y_train), enable_categorical=True)
  dtest_reg = xgb.DMatrix(np.vstack(X_test), np.vstack(y_test), enable_categorical=True)
  params = {"objective": "reg:squarederror", "tree_method": "hist"}
  model = xgb.train(dtrain=dtrain_reg,params=params, num_boost_round=100)
  preds = model.predict(dtest_reg)
  df_test = pd.DataFrame(y_test)
  y_test =np.array(df_test.replace(to_replace=0, method='ffill'))
  #print(y_test,preds)
  mape = np.mean(np.abs((preds- y_test)/y_test))*100
  return(mape)

In [ ]:
xgbst(df)

133073922.56016631

## Grey Kite


In [ ]:
from greykite.framework.templates.autogen.forecast_config import ForecastConfig
from greykite.framework.templates.autogen.forecast_config import MetadataParam
from greykite.framework.templates.forecaster import Forecaster 
from greykite.framework.templates.model_templates import ModelTemplateEnum
from greykite.framework.utils.result_summary import summarize_grid_search_results

In [ ]:
def grey_kite(df_grey):
  train = df_grey[:-15]
  test = df_grey[-15:]
  metadata = MetadataParam(
     time_col="point_timestamp",  # name of the time column
     value_col="point_value",  # name of the value column
     freq="D"  #"MS" for Montly at start date, "H" for hourly, "D" for daily, "W" for weekly, etc.
   )
  forecaster = Forecaster()
  result = forecaster.run_forecast_config(df=train,config=ForecastConfig(model_template=ModelTemplateEnum.SILVERKITE.name,forecast_horizon=15,coverage=0.95,metadata_param=metadata))
  #forecast = result.forecast
  #print(forecast)

In [ ]:
grey_kite(df.query("id == 3"))

## ETS Model


In [17]:
from statsmodels.tsa.exponential_smoothing.ets import ETSModel

In [18]:
def ets(df_ets):
  train =pd.Series(df_ets[:-15]['point_value']).astype('float64')
  print(train)
  test = df_ets[-15:]['point_value']
  model = ETSModel(train)
  fit = model.fit(maxiter=10000)
  #fit.fittedvalues.plot(label="statsmodels fit")
  #print(fit.summary())
  fc = fit.forecast(15)
  y_test =np.array(test.replace(to_replace=0, method='ffill'))
  #print(y_test,preds)
  mape = np.mean(np.abs((fc- y_test)/fc))*100
  return mape 


In [ ]:
ets(df.query("id ==3")[['point_timestamp','point_value']])

0      3512074.0
1      3508261.0
2      3481300.0
3      3507154.0
4      3502240.0
         ...    
241    4330623.0
242    4355175.0
243    4365450.0
244    4369586.0
245    4393149.0
Name: point_value, Length: 246, dtype: float64


0.8391987782270569

## LSTM

In [ ]:
from scalecast.Forecaster import Forecaster

ModuleNotFoundError: ignored

In [ ]:
def lstm(df_lstm):
  train = df_lstm[:-15]
  test = df_lstm[-15:]
  f = Forecaster(y=train['point_value'],current_dates=train['point_timestamp'] )
  f.set_test_length(12)       # 1. 12 observations to test the results
  f.generate_future_dates(15) # 2. 12 future points to forecast
  f.set_estimator('lstm')
  print(f)

In [ ]:
lstm(df.query("id ==3")[['point_timestamp','point_value']])

In [35]:
df.query("id ==9")['point_timestamp'][0][:10]

'2022-12-08'

## NeuralProphet 

In [22]:
from neuralprophet import NeuralProphet

In [23]:
def neural_prophet(df_nr_pr):
  df_nr_pr.rename(columns={'point_timestamp': 'ds', 'point_value': 'y'}, inplace=True)
  train = df_nr_pr[:-15]
  test = df_nr_pr[-15:]['y']
  model = NeuralProphet()
  metrics = model.fit(train, freq="D") 
  future = model.make_future_dataframe(train, periods=15, n_historic_predictions= False) 
  forecast = model.predict(future)
  fc = forecast[-15:]['yhat1']
  y_test =np.array(test.replace(to_replace=0, method='ffill'))
  #print(y_test,preds)
  mape = np.mean(np.abs((fc- y_test)/fc))*100
  print(forecast[-15:])
  return mape 
  

In [ ]:
neural_prophet(df.query("id ==3")[['point_timestamp','point_value']])

In [24]:
g = []
mod = []

for i in range(1,17):
  #arima(df.query("id == 3"))
  print("&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                 ",i)
  mape = []
  mape.append(arima(df.query("id == "+str(i))))
  #mape.append(prophet(df.query("id =="+str(i))[['point_timestamp','point_value']]))
  mape.append(xgbst(df.query("id =="+str(i))))
  mape.append(ets(df.query("id =="+str(i))[['point_timestamp','point_value']]))
  mape.append(neural_prophet(df.query("id =="+str(i))[['point_timestamp','point_value']]))
  print(mape)
  g.append(mape)
  siz = df.query("id == "+str(i)).shape[0]
  for j in range(siz):
    mod.append(mape.index(min(mape)))

&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  1


WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 98.333% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 98.333% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO:NP.utils:Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO - (NP.utils.set_auto_seasonalities) - Disabling weekly seasonality. Run NeuralProphet with weekly_seasonality=True to override this.
INFO:NP.ut

0      7312504.0
1      7903107.0
2      8376171.0
3      6440786.0
4      7267653.0
5      7907051.0
6      8320562.0
7      6271015.0
8      7213831.0
9      7825411.0
10     8253185.0
11     8374123.0
12     7004595.0
13     7700658.0
14     8245303.0
15     8507232.0
16     6931485.0
17     7687782.0
18     8187148.0
19     8586299.0
20     8635373.0
21     7257620.0
22     8036098.0
23     8582487.0
24     8786461.0
25     7462244.0
26     7993143.0
27     8504759.0
28     8899004.0
29     7193594.0
30     8542699.0
31     9390445.0
32    10275528.0
33    10412450.0
34     7982567.0
35     8788194.0
36     9338953.0
37     9638866.0
38     7649180.0
39     8438143.0
40     9126227.0
41     9640369.0
42     7273400.0
43     8197997.0
44     8880845.0
45     9466124.0
46     9569838.0
47     8068219.0
48     8711736.0
49     9127091.0
50     9395938.0
51     6901946.0
52     8001463.0
53     8741565.0
54     9399657.0
55     9471669.0
56     8262678.0
57     9132246.0
58     9692778

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.9/dist-packages/lightning_fabric/accelerators/cuda.py:236: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

  warnings.warn("Can't initialize NVML")

WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

  warnings.warn("Can't initialize NVML")

WARNING - (NP.config.set_lr_finder_args) - Learning rate finder: The number of batches (4) is too small than the required number for the learning rate finder (205). The results might not be optimal.


Finding best initial lr:   0%|          | 0/205 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 98.333% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 98.333% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils

Predicting: 4it [00:00, ?it/s]

INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column


           ds     y      yhat1      trend
0  2022-03-01  None  9183037.0  9183037.0
1  2022-03-02  None  9188755.0  9188755.0
2  2022-03-03  None  9194473.0  9194473.0
3  2022-03-04  None  9200191.0  9200191.0
4  2022-03-05  None  9205909.0  9205909.0
5  2022-03-06  None  9211627.0  9211627.0
6  2022-03-07  None  9217345.0  9217345.0
7  2022-03-08  None  9223063.0  9223063.0
8  2022-03-09  None  9228781.0  9228781.0
9  2022-03-10  None  9234499.0  9234499.0
10 2022-03-11  None  9240216.0  9240216.0
11 2022-03-12  None  9245935.0  9245935.0
12 2022-03-13  None  9251652.0  9251652.0
13 2022-03-14  None  9257370.0  9257370.0
14 2022-03-15  None  9263088.0  9263088.0
[11.861118586459902, 12.709593729130681, 8.990568575890082, 7.5818854330681456]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  2


WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 98.333% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 98.333% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO:NP.utils:Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO - (NP.utils.set_auto_seasonalities) - Disabling weekly seasonality. Run NeuralProphet with weekly_seasonality=True to override this.
INFO:NP.ut

0      53423552.0
1      56541361.0
2      55957540.0
3      56278317.0
4      50410674.0
5      55480111.0
6      53959938.0
7      85079264.0
8     128140930.0
9     121860682.0
10     91465490.0
11    103695447.0
12    139982927.0
13    139608498.0
14    148428022.0
15    126702738.0
16    137301402.0
17    143723675.0
18    139895574.0
19    130016186.0
20    119786495.0
21    138928957.0
22    162532677.0
23    157240332.0
24    150771145.0
25    125368583.0
26    104031209.0
27    114136965.0
28    104893951.0
29    119783178.0
30    137110246.0
31    143378818.0
32    158513329.0
33    135151431.0
34    103630669.0
35    130195598.0
36    139917298.0
37    137881050.0
38    106122848.0
39    114951092.0
40    141703435.0
41    128838258.0
42    143372436.0
43    108328835.0
44    128838623.0
45    177421862.0
46    136663617.0
47    155435478.0
48    140864666.0
49    101642220.0
50     98050621.0
51    126711223.0
52    145621585.0
53    159626038.0
54    132875177.0
55    1477

WARNING - (NP.config.set_lr_finder_args) - Learning rate finder: The number of batches (4) is too small than the required number for the learning rate finder (205). The results might not be optimal.


Finding best initial lr:   0%|          | 0/205 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 98.333% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 98.333% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils

Predicting: 4it [00:00, ?it/s]

INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.9/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'

  warn('Too few observations to estimate starting parameters%s.'



           ds     y        yhat1        trend
0  2022-03-01  None  142430032.0  142430032.0
1  2022-03-02  None  142513344.0  142513344.0
2  2022-03-03  None  142596640.0  142596640.0
3  2022-03-04  None  142679936.0  142679936.0
4  2022-03-05  None  142763248.0  142763248.0
5  2022-03-06  None  142846544.0  142846544.0
6  2022-03-07  None  142929856.0  142929856.0
7  2022-03-08  None  143013152.0  143013152.0
8  2022-03-09  None  143096448.0  143096448.0
9  2022-03-10  None  143179760.0  143179760.0
10 2022-03-11  None  143263072.0  143263072.0
11 2022-03-12  None  143346368.0  143346368.0
12 2022-03-13  None  143429664.0  143429664.0
13 2022-03-14  None  143512976.0  143512976.0
14 2022-03-15  None  143596272.0  143596272.0
[13.413231038717246, 27.91858194950157, 11.034375707495183, 12.033749629841457]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  3


WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 66.667% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 66.667% of the data.
WARNING - (NP.df_utils._infer_frequency) - Dataframe has multiple frequencies. It will be resampled according to given freq D. Ignore message if actual frequency is any of the following:  SM, BM, CBM, SMS, BMS, CBMS, BQ, BQS, BA, or, BAS.
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO:NP.utils:Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO - (NP.u

0    15303.926960
1    11366.153709
2    28798.593280
Name: point_value, dtype: float64


Finding best initial lr:   0%|          | 0/200 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

           ds     y         yhat1         trend
0  2022-04-05  None  31227.437500  31227.437500
1  2022-04-06  None  33687.968750  33687.968750
2  2022-04-07  None  36148.496094  36148.496094
3  2022-04-08  None  38609.027344  38609.027344
4  2022-04-09  None  41069.554688  41069.554688
5  2022-04-10  None  43530.085938  43530.085938
6  2022-04-11  None  45990.613281  45990.613281
7  2022-04-12  None  48451.140625  48451.140625
8  2022-04-13  None  50911.671875  50911.671875
9  2022-04-14  None  53372.203125  53372.203125
10 2022-04-15  None  55832.726562  55832.726562
11 2022-04-16  None  58293.261719  58293.261719
12 2022-04-17  None  60753.785156  60753.785156
13 2022-04-18  None  63214.316406  63214.316406
14 2022-04-19  None  65674.851562  65674.851562
[60.30341854460293, 75.8214340091331, 144.9319199239256, 22.77594870859084]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  4


WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 99.02% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 99.02% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO:NP.utils:Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO - (NP.utils.set_auto_seasonalities) - Disabling weekly seasonality. Run NeuralProphet with weekly_seasonality=True to override this.
INFO:NP.util

0      78.702278
1      78.547686
2      78.028406
3      78.215871
4      79.057359
         ...    
97     79.855086
98     80.755890
99     81.179954
100    81.120868
101    79.938237
Name: point_value, Length: 102, dtype: float64


WARNING - (NP.config.set_lr_finder_args) - Learning rate finder: The number of batches (7) is too small than the required number for the learning rate finder (207). The results might not be optimal.


Finding best initial lr:   0%|          | 0/207 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency W-MON corresponds to 99.02% of the data.
INFO:NP.df_utils:Major frequency W-MON corresponds to 99.02% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency W-MON
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:D

Predicting: 7it [00:00, ?it/s]

INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.9/dist-packages/statsmodels/base/model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

  warnings.warn("Maximum Likelihood optimization failed to "



           ds     y      yhat1      trend
0  2022-04-05  None  81.347282  81.347282
1  2022-04-06  None  81.353569  81.353569
2  2022-04-07  None  81.359863  81.359863
3  2022-04-08  None  81.366150  81.366150
4  2022-04-09  None  81.372444  81.372444
5  2022-04-10  None  81.378731  81.378731
6  2022-04-11  None  81.385025  81.385025
7  2022-04-12  None  81.391312  81.391312
8  2022-04-13  None  81.397598  81.397598
9  2022-04-14  None  81.403893  81.403893
10 2022-04-15  None  81.410179  81.410179
11 2022-04-16  None  81.416473  81.416473
12 2022-04-17  None  81.422760  81.422760
13 2022-04-18  None  81.429054  81.429054
14 2022-04-19  None  81.435341  81.435341
[1.6215079580479768, 2.967015165039659, 1.3993940834015302, 1.641661736246675]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  5


WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency MS corresponds to 80.0% of the data.
INFO:NP.df_utils:Major frequency MS corresponds to 80.0% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency MS
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO:NP.utils:Disabling yearly seasonality. Run NeuralProphet with yearly_seasonality=True to override this.
INFO - (NP.utils.set_auto_seasonalities) - Disabling weekly seasonality. Run NeuralProphet with weekly_seasonality=True to override this.
INFO:NP.utils:Disabling

0    0.000364
1    0.000313
2    0.000079
3    0.000044
4    0.000000
5    0.000073
6    0.000171
7    0.000079
8    0.000000
9    0.000050
Name: point_value, dtype: float64


Finding best initial lr:   0%|          | 0/201 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency MS corresponds to 80.0% of the data.
INFO:NP.df_utils:Major frequency MS corresponds to 80.0% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency MS
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined freq

Predicting: 1it [00:00, ?it/s]

INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column


           ds     y     yhat1     trend
0  2018-10-02  None  0.000027  0.000027
1  2018-10-03  None  0.000026  0.000026
2  2018-10-04  None  0.000025  0.000025
3  2018-10-05  None  0.000025  0.000025
4  2018-10-06  None  0.000024  0.000024
5  2018-10-07  None  0.000024  0.000024
6  2018-10-08  None  0.000023  0.000023
7  2018-10-09  None  0.000023  0.000023
8  2018-10-10  None  0.000022  0.000022
9  2018-10-11  None  0.000022  0.000022
10 2018-10-12  None  0.000021  0.000021
11 2018-10-13  None  0.000020  0.000020
12 2018-10-14  None  0.000020  0.000020
13 2018-10-15  None  0.000019  0.000019
14 2018-10-16  None  0.000019  0.000019
[43.791580901998614, 115.0146328506402, 242.8232506202055, 1517.9854631613405]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&                  6


WARNING - (py.warnings._showwarnmsg) - /usr/local/lib/python3.9/dist-packages/statsmodels/base/model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

  warnings.warn("Maximum Likelihood optimization failed to "

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency MS corresponds to 80.0% of the data.
INFO:NP.df_utils:Major frequency MS corresponds to 80.0% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency MS
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
INFO:NP.config:Setting normalization to global as only one dataframe provided for training.
INFO - (NP.utils.set_auto_seasonalities) - Disabling yearly seasonality. Run NeuralPr

0    0.189965
1    0.194519
2    0.184860
3    0.189654
4    0.183070
5    0.196584
6    0.199722
7    0.177511
8    0.180463
9    0.180877
Name: point_value, dtype: float64


WARNING - (NP.config.set_lr_finder_args) - Learning rate finder: The number of batches (1) is too small than the required number for the learning rate finder (201). The results might not be optimal.


Finding best initial lr:   0%|          | 0/201 [00:00<?, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency MS corresponds to 80.0% of the data.
INFO:NP.df_utils:Major frequency MS corresponds to 80.0% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency MS
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined freq

Predicting: 1it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

INFO - (NP.df_utils._infer_frequency) - Major frequency MS corresponds to 90.769% of the data.
INFO:NP.df_utils:Major frequency MS corresponds to 90.769% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency MS
INFO - (NP.df_utils.return_df_in_original_format) - Returning df with no ID column
INFO:NP.df_utils:Returning df with no ID column
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined frequency is equal to major frequency - D
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 93.333% of the data.
INFO:NP.df_utils:Major frequency D corresponds to 93.333% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO:NP.df_utils:Defined 

TypeError: ignored

In [ ]:
df.drop('Model',axis =1, inplace = True)

KeyError: ignored

In [ ]:
df['Model'] = mod

ValueError: ignored

In [ ]:
df['Model'].value_counts()

4    2478
3     343
0     335
2     189
Name: Model, dtype: int64

In [ ]:
g

In [ ]:
df.tail(10)

point_timestamp  point_value  id  Model
465      2023-01-23     562655.0  10      4
466      2023-01-24     675023.0  10      4
467      2023-01-25     738295.0  10      4
468      2023-01-26     597146.0  10      4
469      2023-01-27     540962.0  10      4
470      2023-01-28         27.0  10      4
471      2023-01-29     153181.0  10      4
472      2023-01-30     541232.0  10      4
473      2023-01-31     712411.0  10      4
474      2023-02-01          1.0  10      4

In [ ]:
df.head(10)

point_timestamp  point_value  id  Model
0      2019-07-14          6.0   1      4
1      2019-07-15          7.0   1      4
2      2019-07-16          6.0   1      4
3      2019-07-17          6.0   1      4
4      2019-07-18          7.0   1      4
5      2019-07-19          6.0   1      4
6      2019-07-20          7.0   1      4
7      2019-07-21          6.0   1      4
8      2019-07-22          6.0   1      4
9      2019-07-23          6.0   1      4

In [ ]:
print(df_features.head(5))

              point_value__sum_values  point_value__median  point_value__mean  \
1 2019-08-07                    155.0                  6.0               6.20   
  2019-08-08                    155.0                  6.0               6.20   
  2019-08-09                    154.0                  6.0               6.16   
  2019-08-10                    154.0                  6.0               6.16   
  2019-08-11                    154.0                  6.0               6.16   

              point_value__length  point_value__standard_deviation  \
1 2019-08-07                 25.0                         0.400000   
  2019-08-08                 25.0                         0.400000   
  2019-08-09                 25.0                         0.366606   
  2019-08-10                 25.0                         0.366606   
  2019-08-11                 25.0                         0.366606   

              point_value__variance  point_value__root_mean_square  \
1 2019-08-07          

In [ ]:
temp_df=(df.groupby(['id','Model']).size().reset_index().rename(columns={0:'count'}))
#df.id.unique()
#df[['id','Model']]
model_df = temp_df[['id','Model']]

In [ ]:
df_features.index

MultiIndex([( 1, '2019-08-07'),
            ( 1, '2019-08-08'),
            ( 1, '2019-08-09'),
            ( 1, '2019-08-10'),
            ( 1, '2019-08-11'),
            ( 1, '2019-08-12'),
            ( 1, '2019-08-13'),
            ( 1, '2019-08-14'),
            ( 1, '2019-08-15'),
            ( 1, '2019-08-16'),
            ...
            (10, '2023-01-23'),
            (10, '2023-01-24'),
            (10, '2023-01-25'),
            (10, '2023-01-26'),
            (10, '2023-01-27'),
            (10, '2023-01-28'),
            (10, '2023-01-29'),
            (10, '2023-01-30'),
            (10, '2023-01-31'),
            (10, '2023-02-01')],
           length=3105)

In [ ]:
t = []
for i in df_features.index:
    t.append(int(model_df.query("id =="+str(i[0]))['Model']))
t


[4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,


In [ ]:
len(t)

In [ ]:
df_features.shape

(3105, 10)

In [ ]:
df_features['Model'] = t

In [ ]:
df_features['Model'].value_counts()

4    2334
3     319
0     287
2     165
Name: Model, dtype: int64

In [ ]:
final_data = df_features

## Classification Algorithm

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

# for modeling
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

In [ ]:
final_data.head(10)

In [ ]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3105 entries, (1, '2019-08-07') to (10, '2023-02-01')
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   point_value__sum_values          3105 non-null   float64
 1   point_value__median              3105 non-null   float64
 2   point_value__mean                3105 non-null   float64
 3   point_value__length              3105 non-null   float64
 4   point_value__standard_deviation  3105 non-null   float64
 5   point_value__variance            3105 non-null   float64
 6   point_value__root_mean_square    3105 non-null   float64
 7   point_value__maximum             3105 non-null   float64
 8   point_value__absolute_maximum    3105 non-null   float64
 9   point_value__minimum             3105 non-null   float64
 10  Model                            3105 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 318.6+ KB


In [ ]:
Y = final_data['Model']
X = final_data.drop(['Model'], axis=1)

print(X.shape)
print(Y.shape)

# convert to numpy arrays
X = np.array(X)

(3105, 10)
(3105,)


In [ ]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

print(encoded_Y)
print(dummy_y)

[3 3 3 ... 3 3 3]
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [ ]:
model = Sequential()
model.add(Dense(16, input_shape=(X.shape[1],), activation='relu')) 
model.add(Dense(4, activation='softmax'))
model.summary()

# compile the model
model.compile(optimizer='rmsprop', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 16)                176       
                                                                 
 dense_13 (Dense)            (None, 4)                 68        
                                                                 
Total params: 244
Trainable params: 244
Non-trainable params: 0
_________________________________________________________________


In [ ]:
X

array([[1.5500000e+02, 6.0000000e+00, 6.2000000e+00, ..., 7.0000000e+00,
        7.0000000e+00, 6.0000000e+00],
       [1.5500000e+02, 6.0000000e+00, 6.2000000e+00, ..., 7.0000000e+00,
        7.0000000e+00, 6.0000000e+00],
       [1.5400000e+02, 6.0000000e+00, 6.1600000e+00, ..., 7.0000000e+00,
        7.0000000e+00, 6.0000000e+00],
       ...,
       [1.2006703e+07, 5.6265500e+05, 4.8026812e+05, ..., 7.8058900e+05,
        7.8058900e+05, 2.7000000e+01],
       [1.2096657e+07, 5.6265500e+05, 4.8386628e+05, ..., 7.8058900e+05,
        7.8058900e+05, 2.7000000e+01],
       [1.1825929e+07, 5.6265500e+05, 4.7303716e+05, ..., 7.8058900e+05,
        7.8058900e+05, 1.0000000e+00]])

In [ ]:
history = model.fit(X,dummy_y,epochs=1000, batch_size=10, shuffle=True, validation_split=0.2,verbose=1)

Epoch 1/1000
249/249 [==============================] - 5s 17ms/step - loss: 143912000.0000 - accuracy: 0.5753 - val_loss: 0.3098 - val_accuracy: 0.9742
Epoch 2/1000
249/249 [==============================] - 2s 6ms/step - loss: 862358.0000 - accuracy: 0.7709 - val_loss: 28627244.0000 - val_accuracy: 0.0741
Epoch 3/1000
249/249 [==============================] - 1s 4ms/step - loss: 653187.0625 - accuracy: 0.7621 - val_loss: 70921.0859 - val_accuracy: 0.8180
Epoch 4/1000
249/249 [==============================] - 1s 4ms/step - loss: 988343.9375 - accuracy: 0.7597 - val_loss: 19149.1328 - val_accuracy: 0.8341
Epoch 5/1000
249/249 [==============================] - 1s 4ms/step - loss: 525959.4375 - accuracy: 0.7669 - val_loss: 175723072.0000 - val_accuracy: 0.0998
Epoch 6/1000
249/249 [==============================] - 1s 4ms/step - loss: 566650.1875 - accuracy: 0.7448 - val_loss: 236263328.0000 - val_accuracy: 0.0950
Epoch 7/1000
249/249 [==============================] - 1s 3ms/step - l

In [ ]:
history_dict = history.history

# learning curve
# accuracy
acc = history_dict['accuracy']
val_acc = history_dict['val_accuracy']

# loss
loss = history_dict['loss']
val_loss = history_dict['val_loss']

# range of X (no. of epochs)
epochs = range(1, len(acc) + 1)

# plot
# "r" is for "solid red line"
plt.plot(epochs, acc, 'r', label='Training accuracy')
# b is for "solid blue line"
plt.plot(epochs, val_acc, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

In [ ]:
val_acc

In [ ]:
np.unique(y)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

preds = model.predict(X) 
matrix = confusion_matrix(dummy_y.argmax(axis=1), preds.argmax(axis=1))
print(classification_report(dummy_y.argmax(axis=1), preds.argmax(axis=1)))

98/98 [==============================] - 1s 5ms/step
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       287
           1       0.98      1.00      0.99       165
           2       0.97      1.00      0.98       319
           3       0.99      0.96      0.98      2334

    accuracy                           0.97      3105
   macro avg       0.93      0.97      0.95      3105
weighted avg       0.97      0.97      0.97      3105



In [ ]:
predicted = encoder.inverse_transform(preds.argmax(axis=1))

In [ ]:
pp = preds.argmax(axis=1)

In [ ]:
unique, counts = np.unique(predicted, return_counts=True)
print(unique,counts)

[0 2 3 4] [ 333  168  330 2274]


In [ ]:
unique, counts = np.unique(pp, return_counts=True)
print(unique,counts)

[0 1 2 3] [ 333  168  330 2274]


In [ ]:
np.unique(predicted)

array([0, 2, 3, 4])

In [ ]:
from tensorflow.keras.models import model_from_json

In [ ]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model1.h5")
print("Saved model to disk")

Saved model to disk


In [ ]:
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model1.h5")
print("Loaded model from disk")

Loaded model from disk


In [ ]:
p = loaded_model.predict(X)

98/98 [==============================] - 0s 3ms/step


In [ ]:
print(p)

[[0.0000000e+00 0.0000000e+00 1.7580666e-11 9.9999994e-01]
 [0.0000000e+00 0.0000000e+00 1.7580666e-11 9.9999994e-01]
 [0.0000000e+00 0.0000000e+00 2.4519661e-12 9.9999994e-01]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 9.9999994e-01]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 9.9999994e-01]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00]]
